version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.18.3-alpine3.9
    steps:
      - checkout
      - run: yarn
      - run yarn test


workflows:
  build_and_test:
    jobs:
      - build